In [1]:
import numpy as np


In [2]:
arr_1=np.array([1,2,3,4])

In [3]:
print(arr_1)

[1 2 3 4]


In [4]:
type(arr_1)

numpy.ndarray

In [5]:
arr_1.ndim

1

In [6]:
arr_2=np.array([[1,2,3,4],[8,5,6,7]])
print(arr_2)

[[1 2 3 4]
 [8 5 6 7]]


In [7]:
arr_2.ndim

2

In [8]:
arr_1.size

4

In [9]:
arr_2.size

8

In [10]:
arr_1.shape

(4,)

In [11]:
arr_2.shape


(2, 4)

In [12]:
arr_1.dtype

dtype('int32')

In [13]:
arr_2.dtype

dtype('int32')

In [14]:
arr_2

array([[1, 2, 3, 4],
       [8, 5, 6, 7]])

In [15]:
arr_2

array([[1, 2, 3, 4],
       [8, 5, 6, 7]])