# numPy Random sampling

In [1]:
import numpy as np
import random

In [2]:
np.random.random(1)

array([0.59856855])

In [3]:
np.random.random(5)

array([0.92874727, 0.28486768, 0.56929269, 0.75053499, 0.27252514])

In [6]:
np.random.random((3,3)) #for 2d 

array([[0.99804368, 0.41435038, 0.98691686],
       [0.99547298, 0.49008282, 0.60620568],
       [0.98323625, 0.03720738, 0.18721739]])

In [10]:
np.random.random((1,4,4)) #for 3d

array([[[0.69478004, 0.377591  , 0.57428685, 0.54233209],
        [0.9058175 , 0.02798265, 0.94609954, 0.99225894],
        [0.64646049, 0.56982594, 0.30594738, 0.53666521],
        [0.17850821, 0.22273245, 0.53606314, 0.44204658]]])

In [11]:
np.random.randint(1,4)

1

In [12]:
np.random.randint(1,4,(4,4)) #for 2d

array([[1, 3, 1, 3],
       [3, 2, 3, 3],
       [2, 3, 2, 2],
       [3, 1, 1, 1]])

In [20]:
np.random.randint(1,9,(2,4,4))

array([[[2, 8, 3, 4],
        [3, 2, 3, 3],
        [8, 1, 4, 1],
        [6, 6, 4, 7]],

       [[5, 5, 8, 7],
        [1, 6, 1, 1],
        [5, 5, 8, 3],
        [3, 6, 7, 2]]])

In [21]:
np.random.randint(1,9,(2,4,4))


array([[[8, 3, 1, 8],
        [7, 5, 6, 1],
        [1, 3, 3, 6],
        [1, 2, 6, 5]],

       [[5, 8, 8, 4],
        [2, 5, 1, 8],
        [1, 6, 6, 5],
        [8, 6, 4, 3]]])

In [22]:
np.random.seed(10)
np.random.randint(1,9,(2,4,4))


array([[[2, 6, 5, 8],
        [1, 2, 4, 5],
        [2, 6, 1, 6],
        [2, 3, 1, 2]],

       [[1, 3, 1, 7],
        [5, 4, 1, 5],
        [8, 4, 7, 1],
        [4, 3, 7, 2]]])

In [23]:
np.random.seed(10)
np.random.randint(1,9,(2,4,4))


array([[[2, 6, 5, 8],
        [1, 2, 4, 5],
        [2, 6, 1, 6],
        [2, 3, 1, 2]],

       [[1, 3, 1, 7],
        [5, 4, 1, 5],
        [8, 4, 7, 1],
        [4, 3, 7, 2]]])

In [24]:
np.random.rand(3)

array([0.72175532, 0.29187607, 0.91777412])

In [26]:
np.random.rand(3,3)

array([[0.71457578, 0.54254437, 0.14217005],
       [0.37334076, 0.67413362, 0.44183317],
       [0.43401399, 0.61776698, 0.51313824]])

In [27]:
np.random.randn(3,2)

array([[ 1.12369125,  1.67262221],
       [ 0.09914922,  1.39799638],
       [-0.27124799,  0.61320418]])

In [28]:
x=[1,2,3,4]
np.random.choice(x)

4

In [30]:
for i in range(20):
  print(np.random.choice(x))

3
1
3
4
1
4
2
3
4
4
1
2
1
3
1
1
1
2
1
4


In [31]:
np.random.permutation(x)

array([2, 3, 4, 1])

In [32]:
np.random.permutation(x)

array([2, 4, 3, 1])