In [1]:
import numpy as np

In [2]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
mx_1 = np.ones(5)
print(mx_1)

[1. 1. 1. 1. 1.]


In [6]:
mx_1.dtype

dtype('float64')

In [7]:
mx_1s= np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
 mx_2 = np.ones((3,4), dtype = int)
 print(mx_2)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [10]:
nx_1= np.zeros((4,3))
print(nx_1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
nx_1=np.zeros((3,4),dtype=int)
print(nx_1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [12]:
nx_1=np.zeros((3,4),dtype=bool)
print(nx_1)

[[False False False False]
 [False False False False]
 [False False False False]]


In [13]:
nx_1=np.zeros((3,4),dtype=str)
print(nx_1)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [14]:
em_str=" "
print(bool(em_str))

True


In [15]:
em_str=""
print(bool(em_str))

False


In [16]:
em_mx =np.empty((3,3))
print(em_mx)

[[1.06126545e-312 0.00000000e+000 1.06395697e+224]
 [2.25078541e+184 8.60642332e-043 6.52053405e-042]
 [9.27101658e-072 5.10561432e-086 6.27207943e-310]]
