# Numpy  functions:

In [1]:
import numpy as np

# arange()

In [2]:
ar_1=np.arange(1,13)
print(ar_1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
even_1=np.arange(1,13,2)
print(even_1)

[ 1  3  5  7  9 11]


# linspace()

In [4]:
kmp= np.linspace(1,5,4)
print(kmp)

[1.         2.33333333 3.66666667 5.        ]


# reshape()

In [5]:
ar_2 =ar_1.reshape(3,4)
print(ar_2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
ar_3= ar_1.reshape(2,3,2)
print(ar_3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
ar_12=np.arange(1,13).reshape(2,6)
print(ar_12)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel()

In [8]:
ar_12.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [9]:
ar_12.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [10]:
ar_12.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [11]:
ar_12.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])